<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoryWithSlug($slug)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->where('c.slug = :slug')
                ->setParameter('slug',$slug)
            ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
