<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionRepository extends EntityRepository
{

    public function findContributionsOfUser($username, $page, $nbPerPage) {
        $qb = $this->createQueryBuilder('c');

        $query = $qb
            ->leftJoin('c.user', 'u')
            ->addSelect('u')
            ->leftJoin('c.project', 'p')
            ->addSelect('p')
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->orderBy('c.date', 'DESC')
        ;

        $query
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function findContributionsOfUserWithLimit($username, $limit) {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->leftJoin('c.user', 'u')
            ->addSelect('u')
            ->leftJoin('c.project', 'p')
            ->addSelect('p')
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->orderBy('c.date', 'DESC')
            ->setMaxResults($limit)
        ;

        return $qb
            ->getQuery()
            ->getResult();
    }
}
