<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CounterpartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterpartRepository extends EntityRepository
{
    public function findAllWithProjectId($id)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.project', 'pro')
                ->addSelect('pro')
            ->where('pro.id = :id')
                ->setParameter('id', $id)
            ;

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findWithPrice($projectId, $price)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->leftJoin('c.project', 'p')
            ->addSelect('p')
            ->where('p.id = :id')
            ->setParameter('id',$projectId)
            ->orderBy('c.minAmount', 'DESC')
            ->andWhere('c.minAmount <= :price')
            ->setParameter('price',$price)
            ->andWhere('c.nbCounterparts != c.maxCounterparts')
            ->setMaxResults(1)
            ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }
}
