<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends EntityRepository
{
    public function findAllMails()
    {
        $qb = $this->createQueryBuilder('n');
        $qb
            ->select('mail')
            ->orderBy('id','ASC')
        ;
        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findWithMail($mail)
    {
        $qb = $this->createQueryBuilder('n');

        $qb
            ->where('n.mail = :mail')
            ->setParameter('mail', $mail)
            ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
