<?php

namespace Pickl\AppBundle\Repository;

/**
 * ProjectTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTagRepository extends \Doctrine\ORM\EntityRepository
{
}
