<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends EntityRepository {

    public function findAllOrderByLevelMin()
    {
        return $this
            ->createQueryBuilder('r')
            ->orderBy('r.minLevel', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findBiggestRanks($limit)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->orderBy('r.minLevel','DESC')
            ->setMaxResults($limit)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}

