<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends EntityRepository
{
    public function findLastRewards($limit)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->orderBy('r.id','DESC')
            ->setMaxResults($limit)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
