<?php

namespace Pickl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * UserRewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRewardRepository extends EntityRepository
{
    public function findRewardsOfUser($username, $limit) {
        $qb = $this->createQueryBuilder('ru');

        $qb
            ->leftJoin('ru.user', 'u')
                ->addSelect('u')
            ->leftJoin('ru.reward', 'r')
                ->addSelect('r')
            ->where('u.username = :username')
                ->setParameter('username', $username)
            ->orderBy('ru.date', 'DESC')
                ->setMaxResults($limit)
        ;
        return $qb
            ->getQuery()
            ->getResult();
    }

}
